### ISSUE TITLE
Fix: error msg design

### ISSUE THREAD

**Issue by ninadepina** [ChrisvanHvA/Appclusive#138]
lil ugly
![Screenshot 2023-06-28 at 16 32 29](https://github.com/ChrisvanHvA/Appclusive/assets/89778503/50293ee7-85ee-4cb8-8323-76cd2145f4bf)

**Comment by noyamirai** [comment]
ja nogal

**Comment by noyamirai** [comment]
zou nu beetje mooi moeten zijn
