### ISSUE TITLE
dark mode issues button

### ISSUE THREAD

**Issue by ninadepina** [ChrisvanHvA/Appclusive#153]
geen hover/focus states en moet andersom qua login moet volledig gevuld
<img width="315" alt="Screenshot 2023-06-29 at 19 40 15" src="https://github.com/ChrisvanHvA/Appclusive/assets/89778503/71610d11-c807-48f8-a2fa-f20984f20c43">

**Comment by ninadepina** [comment]
hover issue is ook light mode btw. nice!!!! awesome! amaze balls!

**Comment by noyamirai** [comment]
fixed now #slay #cool #noLongerUgly
