### ISSUE TITLE
Responsive/Mobile design

### ISSUE THREAD

**Issue by noyamirai** [ChrisvanHvA/Appclusive#4]
Create a mobile design based on the prototype provided by our product owner. See [this figma file](https://www.figma.com/file/tXgDuCXkzmR5b8U2Ls6NFp/Appclusive?type=design&node-id=0%3A1&t=Drf4U5Qx1ZUHLghk-1)

**Comment by sasjakoning** [comment]
- [ ] Login screen
- [ ] Account creation / design of account creation
- [ ] Revision desktop design
- [ ] grote vinger
